"""
Catálogo de textos que ve el usuario (avisos, errores y estados).

Cómo usarlo:  from presentation.strings import t
              t("rec.saved", file="toma.mp4")  ->  "Toma guardada: toma.mp4"

Para traducir la app, copia el diccionario ES como EN (u otro idioma) con las mismas
claves, tradúcelo y regístralo en CATALOGS. Si falta una clave en un idioma se usa
el texto en español, así una traducción incompleta nunca deja un hueco.

Reglas de redacción (para que todos los avisos se lean igual):
  - Un error dice qué pasó, por qué (si se sabe) y qué puede hacer la persona.
  - Nada de jerga ni de excepciones: el detalle técnico va al registro.
  - Los botones nombran la acción («Reintentar», «Cambiar carpeta»), no «Aceptar».
"""

from typing import Dict

ES: Dict[str, str] = {
    # ---- Acciones (botones de los avisos) ----
    "action.retry": "Reintentar",
    "action.rescan": "Buscar de nuevo",
    "action.connect_phone": "Conectar un móvil",
    "action.phone_guide": "Ver guía para conectar un móvil",
    "action.activate_camera": "Activar cámara",
    "action.details": "Ver detalles",
    "action.change_folder": "Cambiar carpeta",
    "action.open_folder": "Abrir carpeta",
    "action.play": "Reproducir",
    "action.reveal": "Mostrar en la carpeta",
    "action.summary": "Resumen",
    "action.audio_settings": "Ajustes de audio",
    "action.vcam_settings": "Ajustes de la cámara virtual",
    "action.cancel": "Cancelar",
    "action.close": "Cerrar",
    "action.repair_phone": "Reparar conexión",

    # ---- Cámaras y monitor ----
    "scan.searching": "Buscando cámaras…",
    "phone.detected": "Teléfono detectado.",
    "source.back": "«{name}» está de vuelta",
    "source.disconnected": "«{name}» se desconectó. La imagen volverá sola cuando aparezca.",
    "source.locked_while_recording": "Detén la grabación para cambiar de cámara.",
    "rotation.after_recording": "El giro se aplicará al terminar la grabación.",
    "format.label": "Formato de la toma",
    "format.horizontal": "Horizontal 16:9",
    "format.vertical": "Vertical 9:16",
    "vertical.mode.crop": "Recortar",
    "vertical.mode.cw": "Girar ↻",
    "vertical.mode.ccw": "Girar ↺",
    "vertical.phone_note": "El teléfono graba en vertical a resolución completa: {w} × {h}.",
    "vertical.crop_note": ("Recorta el centro de la imagen: {w} × {h}. Para no perder resolución, monta la "
                           "cámara de lado y usa «Girar», o graba con el teléfono."),
    "vertical.rotate_note": "Para una cámara montada de lado: se endereza y grabas en {w} × {h} sin perder resolución.",
    "video.searching.title": "Buscando cámaras…",
    "video.searching.body": "Conecta una webcam, una capturadora o un teléfono. Aparecerán solos en la lista.",
    "video.none.title": "No encontramos cámaras",
    "video.none.body": "Conecta una webcam, una capturadora o un teléfono. Aparecerán solos en la lista de la izquierda.",
    "video.probing.title": "Preparando la cámara…",
    "video.probing.body": "Consultando las resoluciones y los fps que ofrece.",
    "video.connecting.title": "Conectando con la cámara…",
    "video.connecting.body": "La imagen aparecerá aquí en unos segundos.",
    "video.open_failed.title": "No se pudo abrir la cámara",
    "video.open_failed.body": ("Puede que otro programa la esté usando directamente (Zoom, Teams, OBS…). "
                               "Ciérralo, o elige en él la cámara «{vcam}», y pulsa Reintentar."),
    "video.embed_failed.title": "La imagen no llegó al monitor",
    "video.embed_failed.body": ("La cámara tardó demasiado en responder o la está usando otro programa "
                                "(Zoom, Teams, OBS…). Ciérralo y pulsa Reintentar."),
    "video.recording_continues.title": "La grabación continúa",
    "video.recording_continues.body": "No se puede mostrar la vista previa, pero la cámara sigue grabando.",
    "video.reconnecting.title": "Reconectando con «{name}»…",
    "video.reconnecting.body": "La imagen se cortó. Intento {n} de {total}.",
    "video.lost.title": "Se perdió la imagen",
    "video.lost.body": ("No se pudo recuperar la conexión. Puede que otro programa (Zoom, Teams, OBS…) esté "
                        "usando esta cámara directamente, o que se haya desconectado."),
    "video.missing_scrcpy.title": "Falta un componente",
    "video.missing_scrcpy.body": ("No se encontró scrcpy, que se usa para los teléfonos Android. "
                                  "Reinstala UltraCam Studio para recuperarlo."),
    "video.missing_ffmpeg.title": "Falta un componente",
    "video.missing_ffmpeg.body": ("No se encontró FFmpeg, que se usa para las webcams y para guardar las tomas. "
                                  "Reinstala UltraCam Studio para recuperarlo."),
    "video.paused.title": "Cámara liberada",
    "video.paused.body": ("UltraCam dejó de usarla, así que otros programas pueden abrirla.\n"
                          "Pulsa «Activar cámara» para volver a usarla."),
    "pause.blocked_while_recording": "No se puede liberar la cámara mientras grabas.",
    "pause.done": "Cámara liberada: otros programas pueden usarla.",
    "pause.resumed": "Cámara reanudada.",
    "missing.components": "Faltan componentes: {items}. Reinstala UltraCam Studio para recuperarlos.",
    "missing.ffmpeg": "FFmpeg (webcams y guardado)",
    "missing.scrcpy": "scrcpy (teléfonos Android)",

    # ---- Cámara virtual ----
    "vcam.on": "Cámara virtual activada: «{vcam}» muestra {what}",
    "vcam.on.no_source": "la cámara que elijas",
    "vcam.off": "Cámara virtual en pausa: «{vcam}» muestra «Sin señal»",
    "vcam.after_recording": "El cambio en la cámara virtual se aplicará al terminar la grabación.",
    "vcam.unavailable": ("La cámara virtual no está disponible porque falta su driver. "
                         "Reinstala UltraCam Studio para recuperarla."),
    "vcam.failed": ("La cámara «{vcam}» no recibe imagen. Tu cámara se sigue viendo y grabando aquí; "
                    "prueba «Volver a registrar» en los ajustes de la cámara virtual."),
    "vcam.button.live": "●  {vcam}: en vivo",
    "vcam.button.connecting": "●  {vcam}: conectando…",
    "live.connecting": "Conectando…",
    "live.on": "En vivo",
    "live.off": "Sin señal",
    "app.starting": "Iniciando…",
    "app.ready": "Listo.",
    "vcam.button.waiting": "●  {vcam}: sin señal",
    "vcam.button.paused": "○  {vcam}: en pausa",
    "vcam.button.unavailable": "{vcam}: no disponible",

    # ---- Grabación ----
    "rec.ready": "Listo · se guarda en {folder}",
    "rec.ready.space": "Listo · {folder} · {free} libres",
    "rec.pick_camera": "Elige una cámara para grabar",
    "rec.waiting_device": "Esperando al dispositivo",
    "rec.recording": "Grabando «{name}»…",
    "rec.recording.detail": "Video + {n} de audio · se guarda en {folder}",
    "rec.recording.channels_one": "1 canal",
    "rec.recording.channels_many": "{n} canales",
    "rec.starting.detail": "Esperando la primera imagen",
    "rec.saving.detail": "Uniendo video y audio",
    "rec.pill": "REC {time}",
    "rec.window_title": "● REC {time} — {app}",
    "pause.button": "Liberar cámara",
    "pause.button.resume": "▶  Activar",
    "rec.starting.title": "Iniciando la cámara…",
    "rec.starting.body": "La grabación empieza en cuanto llegue la imagen.",
    "rec.start_failed.title": "No se pudo iniciar la grabación",
    "rec.start_failed.body": ("La cámara no respondió. Puede que otro programa la esté usando directamente "
                              "(Zoom, Teams, OBS…); ciérralo y vuelve a intentarlo."),
    "rec.no_frames": "La cámara no envió imagen a tiempo.",
    "rec.closed_on_start": "La cámara se cerró al empezar a grabar.",
    "rec.failed_reason.body": "{reason} Revisa que ningún otro programa esté usando la cámara y vuelve a intentarlo.",
    "rec.camera_lost": "La cámara se desconectó durante la grabación. Se guardó todo lo grabado hasta ese momento.",
    "rec.folder_unwritable": ("No se puede guardar en «{folder}»: la carpeta no existe o no tienes permiso para "
                              "escribir en ella. Elige otra carpeta."),
    "rec.saved": "Toma guardada: {file}",
    "rec.saved.banner": "{file} guardado.",
    "rec.saved.clip": "  Hubo saturación: baja un poco los volúmenes.",
    "rec.saved.clean": "  Sin saturación.",
    "rec.save_failed": ("No se pudo guardar la toma: falló la unión del video y el audio. Los archivos originales "
                        "siguen en la carpeta de grabaciones; «Ver detalles» muestra qué pasó."),
    "rec.wait_saving": "Espera a que termine de guardarse la toma…",
    "rec.cancel": "✕   Cancelar",
    "rec.cancelled": "Grabación cancelada antes de empezar.",

    # ---- Espacio en disco ----
    "disk.full": "No hay espacio para grabar: en {drive} quedan {free}. Libera espacio o elige otra carpeta.",
    "disk.low": ("Queda poco espacio: en {drive} quedan {free}. La grabación se detendrá y guardará sola "
                 "antes de que se llene el disco."),
    "disk.stopped": ("La grabación se detuvo porque el disco {drive} se estaba llenando. "
                     "Se guardó todo lo grabado."),

    # ---- Audio ----
    "audio.after_recording": "Los cambios de audio se aplicarán al terminar la grabación.",
    "audio.busy_recording": "Termina la grabación antes de reiniciar el audio.",
    "audio.restarted": "Motor de audio reiniciado.",
    "audio.device_error": ("No se pudo abrir el dispositivo de audio. Puede estar desconectado o en uso por otro "
                           "programa (con ASIO, solo uno a la vez). El video sigue funcionando."),
    "audio.status.error": "⚠ Audio: el dispositivo no responde",
    "fx.opening": "Abriendo la ventana del efecto…",
    "fx.editing": "Editando el efecto de «{name}». Cierra su ventana para guardar el preset.",
    "fx.saved": "Preset del efecto guardado.",

    # ---- Teléfono y dispositivo ----
    "phone.repairing": "Reiniciando la conexión con teléfonos Android…",
    "phone.repaired": ("Conexión reiniciada. Si el teléfono no aparece, prueba otro cable o puerto y revisa "
                       "el aviso en el teléfono."),
    "phone.other_app": "Otro programa",
    "phone.adb_conflict": ("{apps} usa su propia versión de la herramienta de Android y se pelea con UltraCam "
                           "por el teléfono, que se desconecta una y otra vez. Ciérralo mientras uses el "
                           "teléfono por cable y pulsa «Reparar conexión»."),
    "phone.adb_timeout": ("La conexión con los teléfonos Android no responde. Suele pasar cuando otro programa "
                          "({apps}) usa el teléfono por cable. Ciérralo y pulsa «Reparar conexión»."),
    "hw.opened": "Abriendo el panel del fabricante (puede tardar unos segundos).",
    "hw.failed": "No se pudo abrir el panel del fabricante de esta cámara.",
    "wifi.configuring": "Pasando el teléfono a Wi‑Fi…",
    "wifi.ok": "Listo: ya puedes desconectar el cable. El teléfono sigue conectado por Wi‑Fi.",
    "wifi.need_cable": ("Conecta primero el teléfono por cable y acepta «¿Permitir depuración USB?»; "
                        "después pulsa «Pasar a Wi‑Fi»."),
    "wifi.no_ip": ("El teléfono no está conectado a ninguna red Wi‑Fi. Conéctalo a la misma red que esta PC "
                   "y vuelve a intentarlo."),
    "wifi.other_network": ("El teléfono ({phone}) y esta PC ({pc}) están en redes distintas. Conecta los dos a "
                           "la misma red Wi‑Fi (no la de invitados) y vuelve a intentarlo."),
    "wifi.unreachable": ("El teléfono está en tu red ({phone}), pero esta PC no llega a él. Suele pasar si el "
                         "router aísla los dispositivos (red de invitados o «aislamiento de AP») o si Windows "
                         "marca la red como «Pública»: cámbiala a «Privada» en Configuración › Red e Internet."),
    "wifi.button": "Pasar a Wi‑Fi",
    "wifi.guide.title": "Android sin cable (Wi‑Fi)",
    "wifi.guide.body": ("Conecta el teléfono por cable una vez, pulsa «Pasar a Wi‑Fi» y desconecta el cable: "
                        "seguirá en la lista. Los dos deben estar en la misma red Wi‑Fi. Si se corta, UltraCam "
                        "reconecta solo; tras reiniciar el teléfono hace falta el cable otra vez."),
    "wifi.failed": ("No se pudo pasar el teléfono a Wi‑Fi. Deja el cable conectado mientras se configura, "
                    "comprueba que el teléfono y esta PC estén en la misma red Wi‑Fi y que el cortafuegos "
                    "de Windows no bloquee a UltraCam Studio."),

    # ---- Registro y reportes ----
    "log.copied": "Registro copiado al portapapeles.",
    "report.ready": "Reporte {id} guardado y copiado al portapapeles: pégalo en tu mensaje.",

    # ---- Bienvenida (primera ejecución) ----
    "welcome.window_title": "Bienvenida",
    "welcome.title": "Te damos la bienvenida a UltraCam Studio",
    "welcome.subtitle": "Tres cosas y estás listo para grabar o usar tu cámara en videollamadas.",
    "welcome.step1.title": "1. Elige una cámara",
    "welcome.step1.body": ("Webcams, capturadoras y teléfonos aparecen solos en la lista de la izquierda. "
                           "Para usar tu teléfono, pulsa «Conectar un móvil» y sigue los pasos."),
    "welcome.step2.title": "2. Úsala en Zoom, Teams, OBS…",
    "welcome.step2.body": ("En la configuración de video de esos programas elige la cámara «{vcam}». Muestra "
                           "la cámara que elijas aquí, también cuando cambias de una a otra, con tus ajustes "
                           "de imagen. Con UltraCam Studio cerrado, verán el aviso «UltraCam Studio está "
                           "cerrado» en vez de una pantalla negra."),
    "welcome.step3.title": "3. Graba",
    "welcome.step3.body": ("Pulsa «Grabar». Las tomas se guardan en {folder} con la mezcla y cada canal de "
                           "audio en su propia pista. ¿Contenido para redes? Elige «Vertical 9:16» en el "
                           "panel «Cámara» y no tendrás que recortar después."),
    "welcome.start": "Empezar",
    "welcome.reopen": "Ver la bienvenida de nuevo",

    # ---- Confirmaciones (modales) ----
    "close.title": "Cerrar UltraCam Studio",
    "close.body": ("Los programas que usen la cámara «{vcam}» (Zoom, Teams, OBS…) verán el aviso "
                   "«UltraCam Studio está cerrado» hasta que vuelvas a abrirla."),
    "close.recording.title": "Grabación en curso",
    "close.recording.body": "Hay una grabación en curso. ¿Quieres guardarla antes de cerrar?\n\n{note}",
    "close.recording.save": "Guardar y cerrar",
    "close.recording.discard": "Cerrar sin guardar",
    "reset.title": "Restablecer configuración",
    "reset.body": ("Se borrará toda la configuración (canales, efectos, carpeta de grabación…) y la app se "
                   "cerrará; vuelve a abrirla para empezar de cero. Tus grabaciones no se tocan."),
    "reset.confirm": "Borrar y cerrar",
    "channel.delete.title": "Eliminar canal",
    "channel.delete.body": "Se eliminará el canal «{name}» con sus efectos. No se puede deshacer.",
    "channel.delete.confirm": "Eliminar canal",
    # ---- Textos con datos ----
    "source.waiting_title": "«{name}» se desconectó",
    "phone.old_android": "{name} tiene Android {version}",
    "image.saved_for": "✓  Se guarda solo para {name}.",
    "lens.main": "Objetivo: principal 1×",
    "lens.wide": "Objetivo: gran angular {z}×",
    "lens.zoom": "Objetivo: {z}×",
    "lens.back": "Objetivo: trasera",
    "lens.front": "Objetivo: frontal",
    "lens.other": "Objetivo: {orient} {n} · ID {id}",
    "device.usb_codec": "Conectada por USB · {codec}.",
    "device.app_source": "La imagen la envía la app «{name}» instalada en el teléfono.",
    "channel.default_name": "Canal {n}",
    "audio.status.xruns": " · {n} cortes",
    "settings.vcam.intro": ("«{vcam}» está siempre en Windows, aunque cierres el programa: Zoom, Teams, Discord, "
                            "Google Meet, OBS Studio y los navegadores la ven en su lista de cámaras. Muestra "
                            "siempre la cámara que elijas en UltraCam, también al cambiar de una a otra; el "
                            "botón «Cámara Virtual» de la pantalla principal la pone en pausa. Sin imagen "
                            "muestra el cartel «Sin señal», nunca negro."),
    "settings.vcam.last_error": "Último aviso: {error}",
    "settings.vcam.reregister": "Volver a registrar «{vcam}»",
    "settings.vcam.howto": ("• En OBS Studio:\n"
                            "   1. En el panel «Fuentes», pulsa «+» y elige «Dispositivo de captura de video».\n"
                            "   2. Ponle el nombre que quieras y pulsa «Aceptar».\n"
                            "   3. En «Dispositivo», selecciona «{vcam}».\n\n"
                            "• En Zoom, Discord, Google Meet o Microsoft Teams:\n"
                            "   En la configuración de video, elige «{vcam}» como cámara.\n\n"
                            "• Ajustes al instante:\n"
                            "   El brillo, contraste, saturación y giro que ajustes en UltraCam se ven al "
                            "momento en la cámara virtual.\n\n"
                            "• Junto a OBS:\n"
                            "   «{vcam}» es independiente de la cámara virtual de OBS: puedes usar las dos a la vez."),
    # «Salidas 1-2»: el número de la primera salida se lee de este texto (2.ª palabra, antes del guion).
    "settings.outputs_pair": "Salidas {a}-{b}",
    "settings.input_n": "Entrada {n} · {device}",
    "settings.inputs_pair": "Entradas {a}+{b} (estéreo) · {device}",
    "settings.vst_found": "{n} plugins encontrados",
    "summary.stems_in": "WAV por canal en: {folder}",

    # ---- Etiquetas de la interfaz (botones, títulos, notas) ----
    "ui.main.la_imagen_vuelve_sola_en": "La imagen vuelve sola en cuanto aparezca: no hace falta elegirla otra vez.",
    "ui.main.desconectada": "Desconectada",
    "ui.main.desbloquea_el_telefono_y_acepta": "Desbloquea el teléfono y acepta el aviso «¿Permitir depuración USB?» si aparece.",
    "ui.main.sin_senal": "Sin señal",
    "ui.main.grabando": "Grabando",
    "ui.main.comprueba_que_el_telefono_y": "Comprueba que el teléfono y esta PC sigan en la misma red Wi‑Fi.",
    "ui.main.vuelve_a_conectar_el_cable": "Vuelve a conectar el cable USB (mejor en un puerto azul, USB 3.0).",
    "ui.main.abre_la_app_de_camara": "Abre la app de cámara en el teléfono y déjalo desbloqueado.",
    "ui.main.revisa_el_cable_usb_o": "Revisa el cable USB o prueba otro puerto.",
    "ui.main.buscando_camaras": "Buscando cámaras…",
    "ui.main.sin_camara": "Sin cámara",
    "ui.main.elige_una_camara_en_la": "Elige una cámara en la lista",
    "ui.main.camara_virtual": "Cámara Virtual",
    "ui.main.grabar": "●   Grabar",
    "ui.main.audio_iniciando": "Audio: iniciando…",
    "ui.main.para_que_la_camara_no": "Para que la cámara no pierda el foco cuando mueves las manos, fija enfoque y exposición en manual desde «Enfoque, exposición y balance…».",
    "ui.main.brillo": "Brillo",
    "ui.main.contraste": "Contraste",
    "ui.main.saturacion": "Saturación",
    "ui.main.nitidez": "Nitidez",
    "ui.main.los_ajustes_de_imagen_se": "Los ajustes de imagen se aplican a webcams, capturadoras y apps de cámara. En Android la imagen llega tal cual la procesa el teléfono.",
    "ui.main.h_265_mejor": "H.265 (mejor)",
    "ui.main.h_264_compatible": "H.264 (compatible)",
    "ui.main.registro_y_diagnostico": "Registro y diagnóstico",
    "ui.main.telefono_android": "Teléfono Android",
    "ui.main.wifi": "Wi‑Fi",
    "ui.main.trasera": "Trasera",
    "ui.main.frontal": "Frontal",
    "ui.main.mjpeg_por_hardware": "MJPEG por hardware",
    "ui.main.formato_sin_comprimir": "Formato sin comprimir",
    "ui.main.error_desconocido": "Error desconocido",
    "ui.main.entrada_1": "Entrada 1",
    "ui.main.entrada_2": "Entrada 2",
    "ui.main.audio_aplicando_cambios": "Audio: aplicando cambios…",
    "ui.main.audio_detenido": "Audio detenido",
    "ui.main.carpeta_para_las_grabaciones": "Carpeta para las grabaciones",
    "ui.main.probando_el_cable": "Probando el cable…",
    "ui.main.cuentanos_que_paso_que_hiciste": "Cuéntanos qué pasó (qué hiciste y qué esperabas):",
    "ui.main.reportar_un_problema": "Reportar un problema",
    "ui.main.camaras": "Cámaras",
    "ui.main.tomas_recientes": "Tomas recientes",
    "ui.main.copiar": "Copiar",
    "ui.main.camara": "Cámara",
    "ui.main.mas_ajustes": "Más ajustes",
    "ui.main.sin_girar": "Sin girar",
    "ui.main.mezclador": "Mezclador",
    "ui.main.audio": "Audio…",
    "ui.main.canal": "+ Canal",
    "ui.main.camara_seleccionada": "Cámara seleccionada",
    "ui.main.estilo_rapido": "Estilo rápido",
    "ui.main.imagen": "Imagen",
    "ui.main.restablecer": "Restablecer",
    "ui.main.calidad_del_telefono_android": "Calidad del teléfono Android",
    "ui.main.codec": "Códec",
    "ui.main.calidad_mbps": "Calidad (Mbps)",
    "ui.main.archivo": "Archivo",
    "ui.main.nombre_de_la_sesion": "Nombre de la sesión",
    "ui.main.carpeta": "Carpeta",
    "ui.main.cambiar": "Cambiar…",
    "ui.main.volumen_final": "Volumen final",
    "ui.main.pistas": "Pistas",
    "ui.main.guardar_cada_canal_del_mezclador": "Guardar cada canal del mezclador en su propia pista del MP4",
    "ui.main.sincronia_audio_video": "Sincronía audio / video",
    "ui.main.al_terminar_de_grabar": "Al terminar de grabar",
    "ui.main.guardar_tambien_cada_canal_como": "Guardar también cada canal como WAV",
    "ui.main.mostrar_el_archivo_en_el": "Mostrar el archivo en el Explorador",
    "ui.main.reproducirlo_automaticamente": "Reproducirlo automáticamente",
    "ui.main.mostrar_el_resumen_de_la": "Mostrar el resumen de la toma",
    "ui.main.webcam_usb": "Webcam USB",
    "ui.main.capturadora_hdmi": "Capturadora HDMI",
    "ui.main.camara_virtual_2": "Cámara virtual",
    "ui.main.abre_la_app_del_movil": "Abre la app del móvil",
    "ui.main.necesita_android_12": "Necesita Android 12+",
    "ui.main.falta_autorizar": "Falta autorizar",
    "ui.main.el_telefono_esta_conectado_pero": "El teléfono está conectado, pero no ha autorizado esta PC",
    "ui.main.sin_conexion": "Sin conexión",
    "ui.main.el_telefono_dejo_de_responder": "El teléfono dejó de responder",
    "ui.main.esta_camara_no_ofrece_60": "Esta cámara no ofrece 60 fps.",
    "ui.main.90_gira_a_la_derecha": "90° gira a la derecha. Lo hace el teléfono, así que no pierdes calidad: se aplica a lo que grabas y a lo que ves aquí. La cámara virtual mantiene su tamaño, así que allí la imagen girada sale centrada, con franjas a los lados.",
    "ui.main.capturadora_hdmi_el_enfoque_lo": "Capturadora HDMI. El enfoque lo controla la cámara conectada.",
    "ui.main.imagen_que_envia_otro_programa": "Imagen que envía otro programa (OBS, etc.).",
    "ui.main.abre_el_panel_del_fabricante": "Abre el panel del fabricante. Pon enfoque y exposición en manual si tocas un instrumento.",
    "ui.main.si_ves_una_imagen_de": "Si ves una imagen de espera, abre la app en el teléfono y déjalo desbloqueado.",
    "ui.main.sin_enlace_con_el_driver": "sin enlace con el driver",
    "ui.main.hoy": "Hoy ",
    "ui.main.sistema": "Sistema",
    "ui.main.windows_audio": "Windows Audio",
    "ui.main.sin_dispositivo_principal": "sin dispositivo principal",
    "ui.main.mezcla_final": "MEZCLA FINAL",
    "ui.main.girar_imagen": "Girar imagen",
    "ui.main.monitor": "Monitor",
    "ui.main.mas_mbps_mas_detalle_y": "Más Mbps = más detalle y archivos más grandes. Usa 80 solo con cable USB 3.0.",
    "ui.main.pista_1_la_mezcla_final": "Pista 1: la mezcla final. Luego una pista por canal, en el orden del mezclador.",
    "ui.main.adelantar_o_retrasar_el_audio": "Adelantar o retrasar el audio",
    "ui.main.mjpeg": " · MJPEG",
    "ui.main.usar_la_camara_del_telefono": "Usar la cámara del teléfono por cable requiere Android 12 o superior.",
    "ui.main.alternativa_instala_una_app_de": "Alternativa: instala una app de cámara (Iriun, DroidCam) en el teléfono y en esta PC.",
    "ui.main.desbloquea_el_telefono": "Desbloquea el teléfono.",
    "ui.main.acepta_el_aviso_permitir_depuracion": "Acepta el aviso «¿Permitir depuración USB?» (marca «Permitir siempre»).",
    "ui.main.si_no_aparece_el_aviso": "Si no aparece el aviso, desconecta y vuelve a conectar el cable.",
    "ui.main.desconecta_y_vuelve_a_conectar": "Desconecta y vuelve a conectar el cable.",
    "ui.main.prueba_otro_puerto_usb_idealmente": "Prueba otro puerto USB, idealmente uno azul (USB 3.0).",
    "ui.main.la_lente_la_resolucion_y": "La lente, la resolución y los fps se eligen en el panel «Cámara» de la pantalla principal.",
    "ui.main.probar_velocidad_del_cable": "Probar velocidad del cable",
    "ui.main.neutra": "Neutra",
    "ui.main.mostrar": "Mostrar",
    "ui.main.registro_y_diagnostico_2": "Registro y diagnóstico  ●",
    "ui.main.no_hay_camaras_conectadas": "No hay cámaras conectadas.",
    "ui.main.elige_una_camara_para_ver": "Elige una cámara para ver sus opciones.",
    "ui.main.enfoque_exposicion_y_balance": "Enfoque, exposición y balance…",
    "ui.main.como_conectar_un_telefono": "Cómo conectar un teléfono",
    "ui.main.sigue_los_pasos_que_aparecen": "Sigue los pasos que aparecen en el monitor.",
    "ui.main.detener_y_guardar": "■   Detener y guardar",
    "ui.main.aun_no_hay_tomas_pulsa": "Aún no hay tomas. Pulsa Grabar y aparecerán aquí.",
    "ui.main.reproducir": "Reproducir",
    "ui.main.sin_canales_pulsa_canal_para": "Sin canales. Pulsa «+ Canal» para agregar tu guitarra, micrófono o el audio de la PC.",
    "ui.main.bateria": "Batería",
    "ui.main.enlace": "Enlace",
    "ui.main.no_se_genero_video": "No se generó video.",
    "ui.main.guardando": "Guardando…",
    "ui.main.pasar_a_wifi_sin_cable": "Pasar a Wi‑Fi (sin cable)",
    "ui.main.conectado_por_wifi": "Conectado por Wi‑Fi",
    "ui.main.no_se_pudo_medir": "No se pudo medir.",
    "ui.settings.ninguno": "Ninguno",
    "ui.settings.general": "General",
    "ui.settings.video": "Video",
    "ui.settings.audio": "Audio",
    "ui.settings.canales_y_efectos": "Canales y efectos",
    "ui.settings.grabacion": "Grabación",
    "ui.settings.camara_virtual": "Cámara Virtual",
    "ui.settings.avanzado": "Avanzado",
    "ui.settings.configuracion_ultracam_studio": "Configuración — UltraCam Studio",
    "ui.settings.portable_junto_al_programa": "Portable · junto al programa",
    "ui.settings.guardado_en_tu_perfil_de": "Guardado en tu perfil de Windows",
    "ui.settings.donde_guarda_sus_datos_ultracam": "Dónde guarda sus datos UltraCam Studio y cómo se comporta al abrir.",
    "ui.settings.datos_de_la_aplicacion": "Datos de la aplicación",
    "ui.settings.restablecer": "Restablecer",
    "ui.settings.borra_la_configuracion_canales_efectos": "Borra la configuración (canales, efectos, carpeta de grabación…) y vuelve a los valores de fábrica. Tus grabaciones no se tocan.",
    "ui.settings.ajustes_de_la_camara_seleccionada": "Ajustes de la cámara seleccionada. La resolución, los fps y la lente están en el panel «Cámara» de la pantalla principal.",
    "ui.settings.el_dispositivo_principal_marca_el": "El dispositivo principal marca el reloj de todo el audio y es por donde te escuchas (Monitor). Para una interfaz como la Behringer UMC usa ASIO: es lo que da la menor latencia.",
    "ui.settings.dispositivo_principal": "Dispositivo principal",
    "ui.settings.formato": "Formato",
    "ui.settings.frecuencia_de_muestreo": "Frecuencia de muestreo",
    "ui.settings.bufer_mas_chico_menos_retraso": "Búfer más chico = menos retraso al escucharte, pero más CPU y riesgo de cortes. Empieza en 128 con ASIO; si oyes chasquidos, sube a 256.",
    "ui.settings.estado": "Estado",
    "ui.settings.cada_canal_es_una_fuente": "Cada canal es una fuente de audio con su cadena de efectos VST3 (por ejemplo, tu guitarra con Tonocracy). Todos se suman en la mezcla final y cada uno se graba en su propia pista.",
    "ui.settings.canal": "Canal",
    "ui.settings.nombre": "Nombre",
    "ui.settings.fuente": "Fuente",
    "ui.settings.mono_al_centro_manda_una": "«Mono al centro» manda una guitarra o un micrófono a ambos oídos. Monitor: te escuchas por la salida del dispositivo principal, sin el retraso de la grabación.",
    "ui.settings.efectos_vst3": "Efectos (VST3)",
    "ui.settings.agregar_efecto": "Agregar efecto…",
    "ui.settings.abre_la_ventana_del_efecto": "Abre la ventana del efecto para elegir el preset (en Tonocracy: tu amp, ToneSnap o cabina). El preset se guarda al cerrar esa ventana y al salir de UltraCam.",
    "ui.settings.buscar_archivo_vst3": "Buscar archivo .vst3…",
    "ui.settings.donde_se_guardan_las_tomas": "Dónde se guardan las tomas y cómo se procesa el audio al terminar.",
    "ui.settings.camara_virtual_de_windows": "Cámara Virtual de Windows",
    "ui.settings.usalo_si_la_camara_no": "Úsalo si la cámara no aparece en otro programa o si moviste la carpeta de UltraCam Studio.",
    "ui.settings.calidad": "Calidad",
    "ui.settings.como_con_una_webcam_cada": "Como con una webcam, cada programa elige la calidad al abrir la cámara: 1080p o 720p a 30 o 60 fps (y 360p). La imagen se encuadra sin deformarse: una fuente vertical se ve centrada, con franjas a los lados.\n\nTus grabaciones no se ven afectadas: guardan la resolución y los fps nativos de la cámara.",
    "ui.settings.como_usarla_en_otros_programas": "Cómo usarla en otros programas",
    "ui.settings.registro_y_diagnostico": "Registro y diagnóstico",
    "ui.settings.carpetas_de_plugins_vst3": "Carpetas de plugins VST3",
    "ui.settings.motor_de_audio": "Motor de audio",
    "ui.settings.el_audio_y_los_efectos": "El audio y los efectos corren en un proceso aparte: si un plugin falla, la app sigue abierta.",
    "ui.settings.entrada_principal": "Entrada principal",
    "ui.settings.salida_del_monitor": "Salida del monitor",
    "ui.settings.en_windows_audio_la_latencia": "En Windows Audio la latencia típica es de 20–50 ms: bien para voz y audio de la PC; para tocar escuchándote, mejor ASIO.",
    "ui.settings.sin_dispositivo_principal_el_audio": "Sin dispositivo principal: el audio corre con reloj interno y no hay monitor.",
    "ui.settings.sin_fuente": "Sin fuente",
    "ui.settings.agrega_un_canal_para_empezar": "Agrega un canal para empezar.",
    "ui.settings.escucharlo_en_el_monitor_audifonos": "Escucharlo en el Monitor (audífonos)",
    "ui.settings.sin_efectos_la_senal_pasa": "Sin efectos. La señal pasa tal cual.",
    "ui.settings.en_windows": "En Windows",
    "ui.settings.enlace_con_la_app": "Enlace con la app",
    "ui.settings.imagen": "Imagen",
    "ui.settings.carpeta_con_plugins_vst3": "Carpeta con plugins VST3",
    "ui.settings.abrir_carpeta": "Abrir carpeta",
    "ui.settings.restablecer_configuracion": "Restablecer configuración…",
    "ui.settings.windows_audio": "Windows Audio",
    "ui.settings.asio_baja_latencia": "ASIO (baja latencia)",
    "ui.settings.no_se_encontraron_drivers_asio": "No se encontraron drivers ASIO. Instala el driver de tu interfaz (p. ej. «UMC Driver» de Behringer) y pulsa «Buscar de nuevo».",
    "ui.settings.driver_asio": "Driver ASIO",
    "ui.settings.con_asio_ultracam_usa_la": "Con ASIO, UltraCam usa la interfaz en exclusiva: cierra Tonocracy standalone (u otro programa ASIO) y usa Tonocracy como efecto dentro de un canal.",
    "ui.settings.latencia_total": "Latencia total",
    "ui.settings.entrada_salida": "Entrada / salida",
    "ui.settings.carga_de_audio": "Carga de audio",
    "ui.settings.cortes": "Cortes",
    "ui.settings.buscar_dispositivos_de_nuevo": "Buscar dispositivos de nuevo",
    "ui.settings.reiniciar_audio": "Reiniciar audio",
    "ui.settings.mono_al_centro": "Mono al centro",
    "ui.settings.estereo": "Estéreo",
    "ui.settings.no_se_pudo_cargar": "   ⚠ no se pudo cargar",
    "ui.settings.subir": "↑ Subir",
    "ui.settings.bajar": "↓ Bajar",
    "ui.settings.elegir_plugin_vst3": "Elegir plugin VST3",
    "ui.settings.registrada": "✓ Registrada",
    "ui.settings.no_registrada": "✕ No registrada",
    "ui.settings.activo": "✓ Activo",
    "ui.settings.sin_enlace": "✕ Sin enlace",
    "ui.settings.mostrar_registro": "Mostrar registro",
    "ui.settings.copiar_registro": "Copiar registro",
    "ui.settings.reportar_un_problema": "Reportar un problema",
    "ui.settings.agregar_carpeta": "Agregar carpeta…",
    "ui.settings.buscar_plugins_de_nuevo": "Buscar plugins de nuevo",
    "ui.settings.reiniciar_motor_de_audio": "Reiniciar motor de audio",
    "ui.settings.configuracion": "Configuración",
    "ui.settings.bufer_muestras": "Búfer (muestras)",
    "ui.settings.nuevo_canal": "+ Nuevo canal",
    "ui.settings.canales": "Canales",
    "ui.settings.no_se_encontraron_plugins": "No se encontraron plugins",
    "ui.settings.eliminar_canal": "Eliminar canal",
    "ui.settings.en_pausa": "○ En pausa",
    "ui.settings.cartel_sin_senal": "○ Cartel «Sin señal»",
    "ui.settings.modo_portable_todo_se_guarda": "Modo portable: todo se guarda en la carpeta «data» junto al programa. Puedes copiar la carpeta completa a otra PC o a una memoria USB y se lleva tu configuración, canales y presets de efectos.",
    "ui.settings.la_carpeta_del_programa_no": "La carpeta del programa no admite escritura, así que los datos se guardan en tu perfil de Windows. Mueve la carpeta del programa a un lugar con permisos (p. ej. Documentos) para usarla portable.",
    "ui.settings.panel_del_driver_asio": "Panel del driver ASIO…",
    "ui.settings.abrir": "Abrir",
    "ui.settings.plugin_vst3": "Plugin VST3",
    "ui.settings.quitar": "Quitar",
    "ui.settings.muchas_interfaces_fijan_el_tamano": "Muchas interfaces fijan el tamaño del búfer ahí.",
    "ui.connect.conectar_un_movil": "Conectar un móvil",
    "ui.connect.android_cable_usb": "Android (cable USB)",
    "ui.connect.requiere_android_12_o_superior": "Requiere Android 12 o superior. Usa un cable USB 3.0 para 4K.",
    "ui.connect.iphone_o_android_sin_cable": "iPhone (o Android sin cable)",
    "ui.connect.tambien_sirven_camo_droidcam_o": "También sirven Camo, DroidCam o EpocCam: se detectan igual.",
    "ui.connect.revisamos_cada_3_segundos_esta": "Revisamos cada 3 segundos. Esta ventana se cierra sola cuando aparezca.",
    "ui.connect.en_ajustes_informacion_del_telefono": "En Ajustes › Información del teléfono, toca 7 veces «Número de compilación».",
    "ui.connect.en_opciones_de_desarrollador_activa": "En Opciones de desarrollador, activa «Depuración USB».",
    "ui.connect.conecta_el_cable_y_acepta": "Conecta el cable y acepta «¿Permitir depuración USB?» en el teléfono.",
    "ui.connect.instala_iriun_webcam_en_el": "Instala Iriun Webcam en el teléfono (App Store / Play Store).",
    "ui.connect.instala_iriun_webcam_para_windows": "Instala Iriun Webcam para Windows en esta PC (iriun.com).",
    "ui.connect.abre_la_app_en_el": "Abre la app en el teléfono con ambos en la misma red Wi‑Fi o por cable.",
    "ui.connect.reiniciando_la_conexion_usb_con": "Reiniciando la conexión USB con teléfonos Android…",
    "ui.connect.conectar_un_movil_como_camara": "Conectar un móvil como cámara",
    "ui.connect.sigue_los_pasos_de_tu": "Sigue los pasos de tu teléfono. Aparecerá solo en la lista de cámaras; no tienes que elegir ningún modo.",
    "ui.connect.buscando_telefonos": "Buscando teléfonos…",
    "ui.connect.mi_telefono_no_aparece": "Mi teléfono no aparece",
    "ui.connect.listo": "Listo",
    "ui.summary.toma_guardada": "Toma guardada",
    "ui.summary.tamano": "Tamaño",
    "ui.summary.listo_en": "Listo en",
    "ui.summary.mezcla_final": "Mezcla final",
    "ui.summary.nueva_toma": "Nueva toma",
    "ui.summary.reproducir": "Reproducir",
    "ui.summary.pistas_dentro_del_mp4": "PISTAS DENTRO DEL MP4",
    "ui.summary.mostrar_en_la_carpeta": "Mostrar en la carpeta",
    "ui.summary.hubo_saturacion_en_algun_momento": "  Hubo saturación en algún momento: baja un poco los volúmenes para la próxima.",
    "ui.summary.sin_saturacion_el_audio_nunca": "  Sin saturación: el audio nunca pasó de 0 dB.",
    "ui.theme.webcam_usb": "Webcam USB",
    "ui.theme.capturadora_hdmi": "Capturadora HDMI",
    "ui.theme.camara_virtual": "Cámara virtual",
    "ui.theme.telefono_via_app_de_camara": "Teléfono vía app de cámara",
    "ui.theme.movil_android": "Móvil Android",
    "ui.theme.estudio": "Estudio",
    "ui.theme.maxima_definicion": "Máxima definición",
    "ui.theme.fluido": "Fluido",
    "ui.theme.prioriza_60_fps": "Prioriza 60 fps",
    "ui.theme.musico": "Músico",
    "ui.theme.manos_en_movimiento": "Manos en movimiento",
    "ui.theme.poca_luz": "Poca luz",
    "ui.theme.sala_oscura": "Sala oscura",
    "ui.theme.para_youtube_y_streaming": "Para YouTube y redes sociales",
    "ui.theme.14_lufs_volumen_parejo_entre": "−14 LUFS · volumen parejo entre videos",
    "ui.theme.solo_evitar_picos": "Solo evitar picos",
    "ui.theme.techo_en_1_dbfs": "Techo en −1 dBFS",
    "ui.theme.sin_cambios": "Sin cambios",
    "ui.theme.tal_como_sono_en_la": "Tal como sonó en la grabación",
}

CATALOGS: Dict[str, Dict[str, str]] = {"es": ES}
LANG = "es"


def t(key: str, **values) -> str:
    """Texto de `key` en el idioma activo, con los valores {entre llaves} sustituidos."""
    text = CATALOGS.get(LANG, ES).get(key) or ES.get(key) or key
    return text.format(**values) if values else text
